"""Service boundaries.

The HTTP layer talks to these and nothing else. Each concern is a separate protocol so a
stub implementation can be replaced with a live one independently, one endpoint at a time,
without the frontend noticing and without a rewrite. Selection happens in api/deps.py.
"""
from __future__ import annotations

from typing import Protocol

from samepart.api import schemas as s


class CatalogueService(Protocol):
    def list_orgs(self) -> list[s.Org]: ...
    def create_org(self, code: str, name: str) -> s.Org: ...
    def start_import(self, req: s.ImportRequest, filename: str, content: bytes) -> s.ImportStatus: ...
    def import_status(self, import_id: str) -> s.ImportStatus: ...


class ReviewService(Protocol):
    def queue(self, group: str | None, cursor: str | None, limit: int) -> s.QueuePage: ...
    def match(self, match_id: int) -> s.MatchDetail: ...
    def decide(self, match_id: int, req: s.DecisionRequest) -> s.DecisionResult: ...


class CheckService(Protocol):
    def check(self, req: s.CheckRequest) -> s.CheckResult: ...


class AnalyticsService(Protocol):
    def summary(self) -> s.AnalyticsSummary: ...
    def savings(self) -> s.SavingsResult: ...
    def rationalisation(self, limit: int) -> s.RationalisationResult: ...
    def audit_flags(self, limit: int) -> s.AuditFlagResult: ...


class GovernanceService(Protocol):
    def info(self) -> s.GovernanceInfo: ...
    def audit(self, cursor: str | None, limit: int, actor: str | None,
              action: str | None) -> s.AuditTrail: ...
    def reverse(self, canonical_id: str, req: s.ReverseRequest) -> s.ReverseResult: ...


class ExportService(Protocol):
    def cross_reference(self, org_code: str | None, limit: int) -> s.CrossReferenceExport: ...
    def migration_plan(self) -> s.MigrationPlan: ...
    def erp_payload(self, canonical_id: str) -> dict: ...


class QuestionService(Protocol):
    def questions(self, cursor: str | None, limit: int) -> s.QuestionPage: ...
    def answer(self, record_id: int, req: s.AnswerRequest) -> s.AnswerResult: ...
    def unresolvable(self, record_id: int, req: s.UnresolvableRequest) -> s.AnswerResult: ...


class FamilyService(Protocol):
    def list_families(self) -> list[s.FamilySummary]: ...
    def load_family(self, yaml_text: str) -> s.FamilyLoadResult: ...
